const shopItems = [
    { name: "Slim Fit Jeans", category: "Men", type: "jeans", price: 1200 },
    { name: "Casual T-shirt", category: "Men", type: "tshirt", price: 600 },
    { name: "Formal Shirt", category: "Men", type: "shirt", price: 1100 },
    { name: "Track Pant", category: "Men", type: "pant", price: 900 },
    { name: "Printed T-shirt", category: "Women", type: "tshirt", price: 750 },
    { name: "Denim Jeans", category: "Women", type: "jeans", price: 1500 },
    { name: "Combo Pack", category: "Men", type: "mix", price: 2000 },
    { name: "Kids Shorts", category: "Kids", type: "pant", price: 500 },
    { name: "Girls Frock", category: "Kids", type: "mix", price: 800 },
    { name: "Oversized Hoodie", category: "Women", type: "tshirt", price: 1300 },
    { name: "Cargo Pants", category: "Men", type: "pant", price: 1400 },
    { name: "Polka Dot Shirt", category: "Women", type: "shirt", price: 1000 },
    { name: "Running Shorts", category: "Men", type: "pant", price: 800 },
    { name: "Ankle Jeans", category: "Women", type: "jeans", price: 1600 },
    { name: "Winter Combo", category: "Women", type: "mix", price: 2200 },
    { name: "Boys T-shirt", category: "Kids", type: "tshirt", price: 450 },
    { name: "School Uniform", category: "Kids", type: "shirt", price: 950 },
    { name: "Ethnic Set", category: "Women", type: "mix", price: 1800 },
    { name: "Linen Shirt", category: "Men", type: "shirt", price: 1250 },
    { name: "Gym Wear Pack", category: "Men", type: "mix", price: 2400 },
];
